version: "2"
services:
  app: # defining a service called app
    container_name: app # add a container_name as well
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"